"""Generate local synthetic narration and timed captions for the real screen capture."""
from pathlib import Path
import json
import re
import wave

from piper import PiperVoice, SynthesisConfig

PROJECT = Path(__file__).resolve().parents[2]
WORK = PROJECT / '.demo-work' / 'screen'
OUT = PROJECT / 'demo'
WORK.mkdir(parents=True, exist_ok=True)
SCENES = [
    ('intro', 'The working project', 14,
     'This is a screen recording of the lead enrichment project in a local browser workspace. The source viewer reads actual project files, and the terminal runs the Python program. Narration is synthetic.'),
    ('structure', 'Code structure and input', 14,
     'The project separates crawling, cleaning, extraction, and orchestration. The input is a JSON array containing the three assignment targets: Postman, Supabase, and Vapi. The README explains environment setup and local execution.'),
    ('run', 'Execute the Python pipeline', 16,
     'I am starting the command with NVIDIA and the free tier only guard enabled. This terminal displays the actual process output. The three companies are processed concurrently, using headless Chromium to render their public websites.'),
    ('clean', 'Clean context before extraction', 18,
     'The crawler discovers relevant company links. The cleaner removes scripts, styles, SVG elements, and navigation boilerplate. It preserves readable text, public emails, and profile associations. The bounded context sent to the language model contains clean evidence, not raw HTML trees.'),
    ('schema', 'Strict structured outputs', 18,
     'Pydantic defines the required overview, target audience, contacts, leadership details, and confidence score. The overview must contain two sentences. Confidence is bounded from zero to one. The extractor checks the schema and verifies that reported entities have supporting evidence.'),
    ('resilience', 'Continue through failures', 16,
     'Each company has its own failure boundary. Missing pages, timeouts, bot blockers, and provider errors are recorded, with bounded retries where appropriate. The other companies can continue. I will remove the remaining waiting time and return to the finished output.'),
    ('postman', 'Inspect the generated JSON', 18,
     'The pipeline has finished. This is the Postman record generated by the command just shown. It includes the company overview, audience, public emails, leadership details, and confidence. Source pages, crawl errors, and token usage are included for review.'),
    ('coverage', 'All three required targets', 14,
     'The combined JSON includes all three companies. Here are the Supabase and Vapi records. Information that the collected pages do not support is left empty. Confidence reflects evidence completeness, rather than guaranteeing every fact.'),
    ('validation', 'Run artifact validation', 18,
     'I am now running the saved output verifier in the terminal. It checks the schema, two sentence summaries, entity evidence, page limits, and token totals. All three records pass. This validation does not make another language model call.'),
    ('finish', 'Usage and submission files', 14,
     'The summary records actual token usage and estimated cost per domain. The zero dollar estimate uses the configured NVIDIA free tier rates. The repository includes modular code, dependencies, setup instructions, tests, sample output, and this screen recording. Thank you.'),
]

voice = PiperVoice.load(str(PROJECT / '.demo-work' / 'en_US-lessac-medium.onnx'))
config = SynthesisConfig(length_scale=0.96, noise_scale=0.55, noise_w_scale=0.7)
timeline = []
combined = bytearray()
rate = 22050
cursor = 0.0
for scene_id, title, minimum, words in SCENES:
    pcm = bytearray(b'\0' * round(rate * .45) * 2)
    cues = []
    for i, sentence in enumerate(re.split(r'(?<=[.!?])\s+', words)):
        path = WORK / f'{scene_id}-{i}.wav'
        with wave.open(str(path), 'wb') as output:
            voice.synthesize_wav(sentence, output, syn_config=config)
        with wave.open(str(path), 'rb') as source:
            assert source.getframerate()==rate and source.getnchannels()==1 and source.getsampwidth()==2
            start = len(pcm)/2/rate
            pcm.extend(source.readframes(source.getnframes()))
            cues.append({'start': start, 'end': len(pcm)/2/rate, 'text': sentence})
        pcm.extend(b'\0' * round(rate*.12) * 2)
    duration = max(minimum, len(pcm)/2/rate+.7)
    pcm.extend(b'\0' * (round(duration*rate)*2-len(pcm)))
    duration = len(pcm)/2/rate
    timeline.append({'id':scene_id,'title':title,'narration':words,'start':cursor,
                     'duration':duration,'captions':cues})
    combined.extend(pcm)
    cursor += duration
    print(f'{scene_id}: {duration:.2f}s', flush=True)
assert 120 <= cursor <= 180, cursor
with wave.open(str(WORK/'narration.wav'),'wb') as output:
    output.setparams((1,2,rate,0,'NONE','not compressed'))
    output.writeframes(combined)
(OUT/'screen-timeline.json').write_text(json.dumps(timeline,indent=2),encoding='utf-8')
print(f'Total: {cursor:.2f}s',flush=True)
